# Generated by Django 5.0.3 on 2024-05-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0002_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
                ('crops', models.ManyToManyField(null=True, to='Production.crop')),
                ('districts', models.ManyToManyField(to='Production.district')),
            ],
        ),
    ]
