# Generated by Django 5.0.3 on 2024-05-10 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0003_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.crop')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.region')),
            ],
        ),
    ]
