# Generated by Django 5.0.3 on 2024-05-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0004_regionalprices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='districts',
            field=models.ManyToManyField(null=True, to='Production.district'),
        ),
    ]
