# Generated by Django 5.0.6 on 2024-05-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0005_alter_region_districts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='crops',
            field=models.ManyToManyField(to='Production.crop'),
        ),
        migrations.AlterField(
            model_name='region',
            name='districts',
            field=models.ManyToManyField(to='Production.district'),
        ),
    ]
