# Generated by Django 5.0.6 on 2024-05-11 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0006_alter_region_crops_alter_region_districts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('name',)},
        ),
    ]
