# Generated by Django 5.0.6 on 2024-06-21 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0007_alter_crop_options_alter_district_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ('name',), 'verbose_name_plural': 'Crops'},
        ),
    ]
