# Generated by Django 6.0.1 on 2026-04-06 06:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Production', '0008_alter_crop_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=123, null=True)),
                ('last_name', models.CharField(max_length=123, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(default='+255', max_length=200)),
                ('status', models.CharField(choices=[('Advancedfarmer', 'Advancedfarmer'), ('MediumFarmer', 'MediumFarmer'), ('Regular', 'Regular')], default='MediumFarmer', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='User_profile/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('address', models.CharField(max_length=125)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_rank', models.IntegerField(blank=True, null=True)),
                ('regional_rank', models.IntegerField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.region')),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ranks',
            },
        ),
        migrations.CreateModel(
            name='OutputVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=120)),
                ('farm_output', models.IntegerField(blank=True, null=True)),
                ('verification_message', models.CharField(max_length=120)),
                ('pending_message', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('verified', 'verified'), ('denied', 'denied')], default='pending', max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('size', models.CharField(max_length=123)),
                ('c_s_date', models.DateTimeField()),
                ('total_output', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_types', to='Production.crop')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districtss', to='Production.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='Production.region')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Farm',
            },
        ),
    ]
