# Generated by Django 5.0.3 on 2024-05-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_farmer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='status',
            field=models.CharField(choices=[('Advancedfarmer', 'Advancedfarmer'), ('MediumFarmer', 'MediumFarmer'), ('Regular', 'Regular')], default='MediumFarmer', max_length=200),
        ),
    ]
