# Generated by Django 5.0.3 on 2024-05-10 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0004_regionalprices'),
        ('User', '0003_alter_farmer_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmer',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('size', models.CharField(max_length=123)),
                ('c_s_date', models.DateTimeField()),
                ('total_output', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('crop_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Production.crop')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.district')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.region')),
            ],
            options={
                'verbose_name': 'Farmer',
            },
        ),
    ]
