# Generated by Django 5.0.6 on 2024-05-11 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_farmer_options_farm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={'verbose_name_plural': 'Farm'},
        ),
        migrations.AddField(
            model_name='farm',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farm',
            name='total_output',
            field=models.FloatField(),
        ),
    ]
