# Generated by Django 5.0.6 on 2024-06-21 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0008_alter_crop_options'),
        ('User', '0005_alter_farm_options_farm_approved_alter_farm_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='crop_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crop_types', to='Production.crop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farm',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districtss', to='Production.district'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farm',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='Production.region'),
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_rank', models.IntegerField(blank=True, null=True)),
                ('regional_rank', models.IntegerField(blank=True, null=True)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.region')),
            ],
            options={
                'verbose_name': 'Ranks',
            },
        ),
    ]
