# Generated by Django 5.0.6 on 2024-06-21 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_farm_crop_type_alter_farm_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=120)),
                ('farm_output', models.IntegerField(blank=True, null=True)),
                ('verification_message', models.CharField(max_length=120)),
                ('pending_message', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('verified', 'verified'), ('denied', 'denied')], default='pending', max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
